### ISSUE TITLE
Add automated Packaging

### ISSUE THREAD

**Issue by gOOvER** [BloodDragon2580/GildenSteuer#3]
plks add automated packageing to your addon, so libs will we all the time up2date

https://authors.curseforge.com/knowledge-base/projects/3451-automatic-packaging

**Comment by BloodDragon2580** [comment]
Is not needed.

**Comment by gOOvER** [comment]
Macht vieles einfacher ;) und vorallem kannst Du Übersetzungen reionbringen. Ist eigetlich auch der normal Weg, um Addons auf CF zu releasen

**Comment by BloodDragon2580** [comment]
Hatte das irgendwann mal übernommen das addon. Wird aber auch nicht groß benutzt. Deswegen lege ich da nicht groß Arbeit rein. Da habe ich andere Addons da lohnt sich die Arbeit 😉

**Comment by gOOvER** [comment]
Schauen wir mal; ich hab nchste Woche Urlaub und werde es dann mal umschreiben und nen PR zukommen lassen; Du musst dann nur noch den Webhook anlegen :) 

ich finde es eigtlich super :) Aber evtl sollte man den Namen ins Englische ändern :) dann werden es mehr nutzen :D

**Comment by BloodDragon2580** [comment]
Namen auf Englisch zu setzten hatte ich auch schon überlegt. PR kannst du sehr gerne machen. Und mach dich dann gleich in den credits mit rein.
