### ISSUE TITLE
Lua Error "attempt to concatenate local 'playerName' (a nil value)"

### ISSUE THREAD

**Issue by lukiono** [BloodDragon2580/GildenSteuer#4]
Greetings, 

the following error showed today when i switched the zone from oribos to the maw;

> 1x GildenSteuer\GildenSteuer-3.4.lua:376: attempt to concatenate local 'playerName' (a nil value)
> [string "@GildenSteuer\GildenSteuer-3.4.lua"]:376: in function `RequestStatus'
> [string "@GildenSteuer\GildenSteuer-3.4.lua"]:420: in function `FillOutgoingQueue'
> [string "@GildenSteuer\GildenSteuer-3.4.lua"]:447: in function <GildenSteuer\GildenSteuer.lua:430>
> 
> Locals:
> self = <table> {
>  SetDefaultModuleLibraries = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
>  EnableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
>  modules = <table> {
>  }
>  baseName = "GildenSteuer"
>  IterateEmbeds = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
>  SecureHook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:336
>  numberMembers = 22
>  guildRealm = "Nozdormu"
>  playerFullName = "Lukionó-Nozdormu"
>  playerName = "Lukionó"
>  RawHookScript = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:395
>  OnGUICommand = <function> defined @GildenSteuer\GildenSteuer.lua:481
>  OnPrintTaxCommand = <function> defined @GildenSteuer\GildenSteuer.lua:473
>  Printf = <function> defined @ElvUI\Libraries\Core\Ace\AceConsole-3.0\AceConsole-3.0.lua:69
>  nextPurgeTimestamp = 1661614160
>  SetDefaultModulePrototype = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
>  PrintPayingTax = <function> defined @GildenSteuer\GildenSteuer.lua:102
>  guildId = "Der flauschige Zirkel - Nozdormu"
>  OnCommReceived = <function> defined @GildenSteuer\GildenSteuer.lua:606
>  defaultModuleState = true
>  nextSyncTimestamp = 1661614085
>  IsEnabled = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
>  GetStatus = <function> defined @GildenSteuer\GildenSteuer.lua:170
>  MAIL_CLOSED = <function> defined @GildenSteuer\GildenSteuer.lua:728
>  DisableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
>  outgoingQueue = <table> {
>  }
>  isReady = true
>  isBankOpened = false
>  GetPlayerHistoryDB = <function> defined @GildenSteuer\GildenSteuer.lua:160
>  RegisterMessage = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
>  GetArgs = <function> defined @ElvUI\Libraries\Core\Ace\AceConsole-3.0\AceConsole-3.0.lua:144
>  ReduceTax = <function> defined @GildenSteuer\GildenSteuer.lua:320
>  isMailOpened = false
>  IsHooked = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:493
>  MigrateDatabase = <function> defined @GildenSteuer\GildenSteuer.lua:227
>  SendCommMessage = <function> defined @ElvUI\Libraries\Core\Ace\AceComm-3.0\AceComm-3.0.lua:87
>  db = <table> {
>  }
>  MAIL_SHOW = <function> defined @GildenSteuer\GildenSteuer.lua:723
>  UnregisterAllComm = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
>  SetEnabledState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
>  Hook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:274
>  enabledState = true
>  Debug = <function> defined @GildenSteuer\GildenSteuer.lua:65
>  RegisterEvent = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
>  PrintTax = <function> defined @GildenSteuer\GildenSteuer.lua:83
>  UpdatePlayerMoney = <function> defined @GildenSteuer\GildenSteuer.lua:276
>  PLAYER_GUILD_UPDATE = <function> defined @GildenSteuer\GildenSteuer.lua:735
>  playerMoney = 4692905373
>  IterateModules = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
>  GetTax = <function> defined @GildenSteuer\GildenSteuer.lua:114
>  RawHook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:313
>  NotifyStatus = <function> defined @GildenSteuer\GildenSteuer.lua:359
>  GetStatusDB = <function> defined @GildenSteuer\GildenSteuer.lua:134
>  PrintGeneralInfo = <function> defined @GildenSteuer\GildenSteuer.lua:79
>  GUI = <table> {
>  }
>  GUI

**Comment by BloodDragon2580** [comment]
At this time i have no play time. With the new wow addon i will come back and look in to this error.

**Comment by BloodDragon2580** [comment]
Hey, can you please test this version? And then let me know if the error is gone or if there are new errors.:

[GildenSteuer.zip](https://github.com/BloodDragon2580/GildenSteuer/files/10049298/GildenSteuer.zip)

**Comment by BloodDragon2580** [comment]
Should now fixed
